### ISSUE TITLE
Use of newer code conventions prevents breaks inclusion in C# 5.0 script project.

### ISSUE THREAD

**Issue by kwilliams1987** [malware-dev/MDK-Mockups#5]
Since the in-game Programming Block only supports C# 5.0, I set the language version of the project to 5.0.

Unfortunately, as the Mockups use C# 6.0+ conventions such as auto-initialized readonlys and string interpolation, I cannot include the mocking framework as a shared project.

I think it makes sense to enforce C# 5.0 code compliance to allow easy inclusion in Programming Block compatible projects.

**Comment by malware-dev** [comment]
The programmable block supports C# 6.
